// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKyfFKpQRNvnTIZoVpP3WftJfXHTCFaeQ',
    appId: '1:504723991193:android:37bc6c22341e5cd44de608',
    messagingSenderId: '504723991193',
    projectId: 'procal-cc113',
    storageBucket: 'procal-cc113.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC43_u83i750VC-3f9NXl1JyLcH_-4cD0g',
    appId: '1:504723991193:ios:7f5ac0817e2234f64de608',
    messagingSenderId: '504723991193',
    projectId: 'procal-cc113',
    storageBucket: 'procal-cc113.firebasestorage.app',
    androidClientId: '504723991193-9qkkn2jqoi2p1ftke8vfs1890h87h30m.apps.googleusercontent.com',
    iosClientId: '504723991193-eu1mogiqdn7b8c0oiddg0u4b9g5u1hek.apps.googleusercontent.com',
    iosBundleId: 'com.example.procal',
  );

}